![image.png](attachment:image.png)

# Numpy

Numpy is THE library for scientific computing and linear algebra in Python's community and was designed to give users the best of both worlds in programming languages: the speed of `C` language with the readability and elegance of `Python`.

### Why Numpy?
A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example we cannot multiply two lists directly we will have to do it element wise. This is where the role of NumPy comes into play.

In [1]:
from numpy import *
import numpy as np

Very quick speed comparison to show the staggering difference in performance, don't bother about the code in the following cell.

In [ ]:
import numpy as np
import time
import gc # garbage collection
import sys


def compare_times(f1, f2, setup1=None, setup2=None, runs=30):
    print('    format: mean seconds (standard error)', runs, 'runs')
    maxpad = max(len(f.__name__) for f in (f1, f2))
    means = []
    for setup, f in [[setup1, f1], [setup2, f2]]:
        setup = (lambda: tuple()) if setup is None else setup
        
        total_times = []
        for _ in range(runs):
            try:
                gc.disable()
                args = setup()
                
                start = time.time()
                if isinstance(args, tuple):
                    f(*args)
                else:
                    f(args)
                end = time.time()
                
                total_times.append(end - start)
            finally:
                gc.enable()
                
        mean = np.mean(total_times)
        se = np.std(total_times) / np.sqrt(len(total_times))
        print('    {} {:.2e} ({:.2e})'.format(f.__name__.ljust(maxpad), mean, se))
        means.append(mean)
    print('    improvement ratio {:.1f}'.format(means[0] / means[1]))

In [ ]:
size = 10 ** 7 
print('create a list 1, 2, ...', size)


def create_list(): return list(range(size))
def create_array(): return np.arange(size, dtype=int)

compare_times(create_list, create_array)

create a list 1, 2, ... 10000000
    format: mean seconds (standard error) 30 runs
    create_list  4.85e-01 (1.10e-02)
    create_array 2.39e-02 (6.99e-04)
    improvement ratio 20.3


In [ ]:
import time
num = 10000000
a = np.random.random(num)
b = np.random.random(num)

star = time.time()
c = np.dot(a,b)
en = time.time()
print(c)
print("Verctorize  : " +  str((en -star)*1000) + 'ms')

d =0
start = time.time()
for i in range(num):
    d += a[i]*b[i]
end = time.time()

print(d)
print("Loop version  : " +  str((end -start)*1000) + 'ms')
print("Vectorization is faster by" , (end -start)/(en -star) , 'times')

2499632.0268662428
Verctorize  : 12.294769287109375ms
2499632.026866403
Loop version  : 4796.185493469238ms
Vectorization is faster by 390.0996742165684 times


### Convinced about numpy powers? ... Now, let's practice!

#### Q1: Create a 1D array of numbers from 0 to 9.


In [13]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2: Extract all odd numbers from arr.


In [14]:
b = np.where(arr % 2 != 0)
arr[b]

array([1, 3, 5, 7, 9])

#### Q3: Replace all odd numbers in arr with -1.


In [15]:
arr[b] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q4: Convert a 1D array of length 10 to a 2D array with 2 rows


In [16]:
arr.reshape((2, 5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

#### Q5: compute the square root for each element in the  array
#### ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [22]:
arr2 = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])
np.sqrt(arr2) 

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.44948974]])

#### Q6: compute the exponential for each element in the above array


In [21]:
np.exp(arr2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [  7.3890561 ,  20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 , 403.42879349]])

#### Q7: sample 8 elements from uniform dist ([0, 1)


In [23]:
arr3 = np.random.uniform(0, 1, 8)
arr3

array([0.26495082, 0.20847707, 0.87225152, 0.52287165, 0.58616509,
       0.22736105, 0.68420758, 0.07704006])

#### Q8: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [45]:
vec = np.random.randint(0, 11, 5)
vec

array([ 3,  1, 10,  6,  0])

#### Q9: Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [51]:
mat = np.linspace(10, 21, 12).reshape(3, 4)
mat

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.]])

#### Q10: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [52]:
vec = np.linspace(5, 50, 10)
vec

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

#### Q11: Write a NumPy program to create an array of all the even integers from 30 to 70.

In [59]:
arr4 = np.arange(30, 71, 2)
arr4

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### Q12: Write a NumPy program to check whether two arrays are equal (element wise) or not

In [70]:
arr1 = np.arange(1, 10)
arr2 = np.arange(1, 10)
res = np.all(arr1 == arr2)
res

True

In [72]:
arr3 = np.array([1, 12, 20, 4, -1, 3, 7, 8, 11])
res = np.all(arr1 == arr3)
res

False

* further reading: [visit here](https://www.w3resource.com/python-exercises/numpy/index.php)